Traceback (most recent call last):
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 498, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 342, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/worker.py", line 2247, in get
    raise value
ray.exceptions.RayTaskError: [36mray_worker[39m (pid=31365, host=jimmy-desktop)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/gym/envs/mujoco/mujoco_env.py", line 12, in <module>
    import mujoco_py
ModuleNotFoundError: No module named 'mujoco_py'

During handling of the above exception, another exception occurred:

[36mray_worker[39m (pid=31365, host=jimmy-desktop)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 87, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 328, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/tune/trainable.py", line 99, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 443, in _setup
    self._init(self.config, self.env_creator)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 103, in _init
    self.workers = make_workers(self, env_creator, policy, config)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/agents/impala/impala.py", line 105, in defer_make_workers
    return trainer._make_workers(env_creator, policy, config, 0)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 488, in _make_workers
    logdir=self.logdir)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 64, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 216, in _make_worker
    _fake_sampler=config.get("_fake_sampler", False))
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 258, in __init__
    self.env = _validate_env(env_creator(env_context))
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 421, in <lambda>
    self.env_creator = lambda env_config: gym.make(env)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/gym/envs/registration.py", line 72, in make
    cls = load(self.entry_point)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/gym/envs/registration.py", line 17, in load
    mod = importlib.import_module(mod_name)
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "/home/jimmy/anaconda3/envs/qrl/lib/python3.7/site-packages/gym/envs/mujoco/mujoco_env.py", line 14, in <module>
    raise error.DependencyNotInstalled("{}. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)".format(e))
gym.error.DependencyNotInstalled: No module named 'mujoco_py'. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)

